# Generated by Django 5.1.4 on 2025-01-16 04:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_image_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(blank=True, help_text="List of user's friends.", related_name='friends_of', to=settings.AUTH_USER_MODEL, verbose_name='Friends'),
        ),
    ]
