# Generated by Django 5.1.4 on 2025-01-05 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the country.', max_length=100, verbose_name='Country Name')),
                ('alpha2', models.CharField(help_text='ISO 3166-1 alpha-2 code of the country (2 letters).', max_length=2, unique=True, validators=[django.core.validators.RegexValidator(message='Alpha-2 code must be exactly two letters.', regex='^[a-zA-Z]{2}$')], verbose_name='Alpha-2 Code')),
                ('alpha3', models.CharField(help_text='ISO 3166-1 alpha-3 code of the country (3 letters).', max_length=3, validators=[django.core.validators.RegexValidator(message='Alpha-3 code must be exactly three letters.', regex='^[a-zA-Z]{3}$')], verbose_name='Alpha-3 Code')),
                ('region', models.CharField(choices=[('Europe', 'Europe'), ('Africa', 'Africa'), ('Americas', 'Americas'), ('Oceania', 'Oceania'), ('Asia', 'Asia')], default='Europe', help_text='Region the country belongs to.', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
