# Generated by Django 5.1.4 on 2025-01-07 05:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The content of the post (up to 1000 characters).', max_length=1000, verbose_name='Content')),
                ('tags', models.JSONField(default=list, help_text='A list of tags associated with this post.', verbose_name='Tags')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='The date and time when the post was created.', verbose_name='Created At')),
                ('likesCount', models.IntegerField(default=0, help_text='The number of likes this post has received.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Likes Count')),
                ('dislikesCount', models.IntegerField(default=0, help_text='The number of dislikes this post has received.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dislikes Count')),
                ('author', models.ForeignKey(help_text='The user who created this post.', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, to_field='login', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
