# Generated by Django 5.1.4 on 2025-01-31 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='dislikesCount',
            new_name='dislikes_count',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='likesCount',
            new_name='likes_count',
        ),
        migrations.AddField(
            model_name='post',
            name='disliked_users',
            field=models.ManyToManyField(help_text='Users who disliked the post', related_name='disliked_posts', to=settings.AUTH_USER_MODEL, verbose_name='Disliked Users'),
        ),
        migrations.AddField(
            model_name='post',
            name='liked_users',
            field=models.ManyToManyField(help_text='Users who liked the post', related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='Liked Users'),
        ),
    ]
